# Generated by Django 2.1.3 on 2019-05-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190503_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.TextField(default='Blogpost'),
            preserve_default=False,
        ),
    ]
